# ===========================================
# PVC : Persistent Volume Claims
# MySQL et Redis sont externes (pas besoin de PVC ici)
# ===========================================

# Cache Laravel (bootstrap/cache)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wave-cache-pvc
  labels:
    app: wave-app
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath

---

# Storage Laravel (storage/)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wave-storage-pvc
  labels:
    app: wave-app
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath
